### ISSUE TITLE
Découper le code en plusieurs fonctions

### ISSUE THREAD

**Issue by Maxime-Dr** [ilyght/CDOF3-TD1#2]
Il faut essayer de rendre le code le plus propre possible. Notamment, en suivant le principe suivant : 

The single responsibility principle (SRP) is a computer programming principle that states that "A module should be responsible to one, and only one, actor."[1]

Avoir une fonction qui fait tout engendre des problèmes lors du processus de troubleshooting ou bien lorsqu'une seconde personne doit utiliser ou relire le code.

**Comment by ilyght** [comment]
merci d'avoir proposé une version améliorée du code !
