### ISSUE TITLE
Enhance README Documentation for Better User Experience

### ISSUE THREAD

**Issue by Magnoir** [ilyght/CDOF3-TD1#8]
The current README provides a good starting point for understanding the project. However, there are several areas where it could be improved to provide a more comprehensive and user-friendly experience. Here are some suggestions:

1. **Project Description**: The project description could be expanded to include more details about the project's purpose, its features, and the problems it solves. This will help users understand what they can expect from using the project.

2. **Installation Instructions**: While the document mentions the need for a functional Python environment, it doesn't provide detailed instructions on how to set up and install the project. This should include any prerequisites needed to run the project and the exact commands to run the script.

3. **Contribution Guidelines**: If the project is open to contributions, include guidelines on how others can contribute. This could include information on how to submit issues, create pull requests, and the project's code of conduct.

4. **License Information**: Include information about the project's license. This helps users understand how they can use the project and any restrictions that might apply.

By implementing these changes, the README will provide a more comprehensive overview of the project, making it easier for users to understand and use.

**Comment by ilyght** [comment]
Great feedback! I appreciate your suggestions for improving the README. Can you contribute to these enhancements? Your input would be valuable in making the project more user-friendly. Thanks!
