### ISSUE TITLE
Handle Edge Cases and Improve User Input Validation

### ISSUE THREAD

**Issue by Magnoir** [ilyght/CDOF3-TD1#9]
Upon reviewing the `main.py` file, there doesn't appear to be any obvious bugs in the code. However, there are a few areas where the code could be improved to handle edge cases and improve user experience.

1. **User Input Validation**: Currently, the program does not validate user input when creating, marking as done, or removing tasks. If a user enters an empty string or a string with only spaces, the program will accept it as a valid task. This could lead to confusion and unexpected behavior. The program should validate user input and ensure that it is not empty or only spaces.

2. **Case Sensitivity**: The program currently treats tasks with the same name but different case as different tasks. For example, "task" and "Task" would be treated as two separate tasks. This could lead to confusion and unexpected behavior. The program should be updated to treat tasks with the same name but different case as the same task.

3. **Duplicate Task Names**: The program currently prevents users from adding tasks with the same name. However, it might be more user-friendly to allow users to add tasks with the same name and provide a warning instead of preventing them from adding the task.

4. **User Input for Menu Options**: The program currently accepts any input for the menu options, even if it's not a number. If a user enters a non-number input, the program should display an error message and ask for input again.

By addressing these issues, the program will be more robust and provide a better user experience.

**Comment by ilyght** [comment]
Thank you for taking the time to review the project and providing valuable feedback! Your insights on user input validation, case sensitivity, handling duplicate task names, and improving input validation for menu options are excellent points. Would you be interested in contributing to these improvements? Your input would be greatly appreciated in enhancing the overall user experience of the program. Thanks again!
